In [5]:
import numpy as np


In [6]:
np.__version__

'2.3.5'

creating array

In [7]:
my_list=[0,1,2,3,4,5]

In [8]:
type(my_list)

list

In [9]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
print(my_list)
print(arr)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


In [11]:
print(my_list)
print(arr)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


arange()

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

zeros()

In [12]:
np.zeros(5) #parameter tuning -- by default float

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5, dtype=int) #hyperparamter tuning

array([0, 0, 0, 0, 0])

In [14]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [15]:
np.zeros((10,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

ones()

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.ones(2)

array([1., 1.])

random

In [20]:
np.random.rand(4)

array([0.19896555, 0.64748152, 0.78985698, 0.34192032])

In [21]:
np.random.rand(3,2)

array([[0.61274883, 0.63842369],
       [0.68278782, 0.64080409],
       [0.56415395, 0.32000727]])

In [23]:
np.random.randint(5)

3

In [25]:
np.random.randint(5,10,3) # gives 3 random nums inbetwn 5 to 10

array([5, 5, 7], dtype=int32)

In [48]:
np.random.randint(5,10,[5,7]) # gives random nums inbetwn 5 to 10 with 5 rows and 7 cols

array([[5, 9, 8, 8, 8, 9, 5],
       [9, 9, 8, 6, 6, 5, 5],
       [9, 7, 9, 7, 7, 7, 6],
       [7, 9, 5, 9, 8, 9, 6],
       [5, 5, 9, 9, 8, 9, 8]], dtype=int32)

In [3]:
np.random.randint(10,2) # first arg always less than second arg

ValueError: low >= high

In [16]:
np.random.randint(-10,2) #gives rand num inbetwn -10 to 2

-3

In [14]:
np.random.randint(-10,4,5) #gives 5 rand nums inbetwn -10  to 4

array([ 3, -7, -8,  1,  1], dtype=int32)

In [37]:
np.random.randint(10,40,(10,10)) # gives 10*10 rand nums inbetwn 10 to 40 (10*10)

array([[16, 19, 32, 30, 38, 11, 36, 22, 35, 26],
       [18, 36, 32, 16, 19, 35, 33, 13, 15, 13],
       [33, 32, 37, 29, 23, 18, 13, 19, 32, 35],
       [30, 15, 11, 28, 22, 23, 26, 38, 21, 35],
       [32, 29, 39, 10, 26, 30, 18, 11, 33, 26],
       [27, 26, 31, 36, 30, 36, 31, 32, 30, 12],
       [24, 14, 13, 17, 36, 17, 18, 15, 34, 30],
       [24, 33, 16, 20, 30, 26, 38, 38, 35, 12],
       [29, 31, 25, 39, 21, 17, 35, 28, 39, 35],
       [25, 26, 15, 34, 24, 26, 13, 30, 29, 25]], dtype=int32)

In [21]:
arr1=np.random.randint(10,40,(10,10))
print(arr1) 

[[18 34 23 38 28 20 21 38 30 17]
 [15 10 26 12 35 37 28 10 27 23]
 [36 15 22 26 38 38 29 11 22 21]
 [13 22 20 25 22 11 27 35 21 10]
 [38 29 13 37 13 32 32 14 29 39]
 [20 38 24 22 28 12 27 21 20 34]
 [31 23 12 36 31 33 17 23 13 29]
 [21 13 11 20 16 35 25 19 25 15]
 [26 22 31 31 14 21 16 11 30 28]
 [11 29 26 28 21 37 17 34 17 27]]


indexing and slicing in array

In [33]:
arr[1:7]

array([1, 2, 3, 4, 5])

In [17]:
arr2 = np.random.randint(1,10,(3,3)) # created 3*3 array with rand nums inbetwn 1 to 10 
arr2

array([[4, 6, 1],
       [9, 6, 2],
       [6, 4, 7]], dtype=int32)

In [18]:
arr2[::-1] # reversed array

array([[6, 4, 7],
       [9, 6, 2],
       [4, 6, 1]], dtype=int32)

In [22]:
arr1

array([[18, 34, 23, 38, 28, 20, 21, 38, 30, 17],
       [15, 10, 26, 12, 35, 37, 28, 10, 27, 23],
       [36, 15, 22, 26, 38, 38, 29, 11, 22, 21],
       [13, 22, 20, 25, 22, 11, 27, 35, 21, 10],
       [38, 29, 13, 37, 13, 32, 32, 14, 29, 39],
       [20, 38, 24, 22, 28, 12, 27, 21, 20, 34],
       [31, 23, 12, 36, 31, 33, 17, 23, 13, 29],
       [21, 13, 11, 20, 16, 35, 25, 19, 25, 15],
       [26, 22, 31, 31, 14, 21, 16, 11, 30, 28],
       [11, 29, 26, 28, 21, 37, 17, 34, 17, 27]], dtype=int32)

In [10]:
arr1[2:5] # printed 2 rows to 5 rows

array([[36, 15, 35, 17, 15, 18, 32, 18, 39, 10],
       [26, 27, 25, 16, 34, 31, 35, 14, 22, 15],
       [23, 29, 35, 11, 33, 38, 36, 36, 20, 27]], dtype=int32)

In [25]:
arr1[2,4] # printed second row's 4th col place number

np.int32(38)

In [9]:
arr1.shape # shape of an array

(10, 10)

In [26]:
len(arr1) 

10

In [29]:
print(arr1[3]) #printed 3rd row

[13 22 20 25 22 11 27 35 21 10]


In [45]:
np.arange(10,20).reshape(10,1) #printed nums 10 to 20 in 1 col

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])