In [2]:
import numpy as np

In [ ]:
#Array creation

In [2]:
a= np.array([1,2,3])
print("array a:",a)

array a: [1 2 3]


In [ ]:
#creating array with even spaced value

In [3]:
b=np.arange(0,10,2)
print("array b:",b)

array b: [0 2 4 6 8]


In [ ]:
#creating array filled with zeros

In [6]:
c=np.zeros((2,3))
print("array c:\n",c)

array c:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#creating array filled with ones

In [9]:
d=np.ones((3,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
#create an indentinty matrix
f=np.eye(4) #4x4 matrix
print("identity matrix f:\n",f)

identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Array manipulation functions

In [14]:
#reshape an array

a1=np.array([1,2,3])
reshaped=np.reshape(a1,(3,1))
print("reshaped arrays:",reshaped)


reshaped arrays: [[1]
 [2]
 [3]]


In [15]:
#flatten an array -- 

f1=np.array([[1,2],[3,4]])
flattened = np.ravel(f1) #flatten to 1d array
print("flattened array:",flattened)

flattened array: [1 2 3 4]


In [16]:
#transpose an array --- reverse rows to colums and cols to rows

e1=np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("transposed array:\n", transposed)

transposed array:
 [[1 3]
 [2 4]]


In [17]:
# stack arrays vertically

a2=np.array([1,2])
b2=np.array([3,4])
stacked = np.vstack([a2,b2])
stacked

array([[1, 2],
       [3, 4]])

In [18]:
# stack arrays horizontally

a2=np.array([1,2])
b2=np.array([3,4])
stacked = np.hstack([a2,b2])
stacked

array([1, 2, 3, 4])

In [ ]:
#mathematical functions

In [19]:
#add two arrays

g=np.array([1,2,3,4])
added=np.add(g,2)
added

array([3, 4, 5, 6])

In [20]:
#square each element

squared = np.power(g,2)
squared

array([ 1,  4,  9, 16])

In [21]:
#square root of each element
sqrt_val=np.sqrt(g)
sqrt_val

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [22]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [23]:
print(a1)
print(a)

[1 2 3]
[1 2 3]


In [24]:
a3=np.array([1,2,3])
dot_product=np.dot(a1,a)
print("dot product of a1 and a:",dot_product)
#(1x1 + 2x2 + 3x3)

dot product of a1 and a: 14


In [ ]:
#dot product shoulnt apply for shape not matched

In [ ]:
#statistical functional

In [25]:
s=np.array([1,2,3,4])
mean=np.mean(s)
print(mean)

2.5


In [26]:
s=np.array([1,2,3,4])
mean=np.var(s)
print(mean)

1.25


In [27]:
#standard dev
std_dev=np.std(s)
print(std_dev)

1.118033988749895


In [28]:
minimum=np.min(s)
print(minimum)

1


In [29]:
maximum=np.max(s)
print(maximum)

4


In [ ]:
#Random sampling

In [3]:
# random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values btw 0 and 1
print("Random values:", random_vals)

Random values: [0.80831241 0.36867934 0.58518839]


In [4]:
np.random.seed(0)

# random values between 0 and 1
random_vals = np.random.rand(3)  # Array of 3 random values between 0 and 1
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [5]:
# random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [6]:
np.random.seed(0)

# Generate random integers
rand_ints = np.random.randint(0, 10, size=5)  # Random integers between 0 and 10
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


In [ ]:
#boolean & logical functuions

In [30]:
logical_test=np.array((True,False,True))
all_true=np.all(logical_test)
print(all_true)

False


In [31]:
any_true=np.any(logical_test)
print(any_true)

True


In [ ]:
#Set operations

In [32]:
#intersection
set_a=np.array([1,2,3,4])
set_b=np.array([3,4,5,6])

intersection = np.intersect1d(set_a,set_b)
print(intersection)

[3 4]


In [33]:
union=np.union1d(set_a,set_b)
print(union)

[1 2 3 4 5 6]


In [ ]:
#Array Attributes functions

In [7]:
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


In [ ]:
#other functions

In [8]:
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [9]:
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [10]:
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
